#include "Bloque.h"


void Bloque::setx(int z)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-12--2b72d78c:140d5a4a071:-8000:0000000000000AA3 begin
{
	x = z;
}
// section -64--88-0-12--2b72d78c:140d5a4a071:-8000:0000000000000AA3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Bloque::sety(int z)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-12--2b72d78c:140d5a4a071:-8000:0000000000000AA5 begin
{
	y = z;
}
// section -64--88-0-12--2b72d78c:140d5a4a071:-8000:0000000000000AA5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Bloque::print_xy() const
{
	std::cout << "X = " << x
            << " Y = " << y
            << std::endl;	
}
