#include "Bloque.h"




void Bloque::setx()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-12--2b72d78c:140d5a4a071:-8000:0000000000000AA3 begin
{
}
// section -64--88-0-12--2b72d78c:140d5a4a071:-8000:0000000000000AA3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Bloque::sety()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-12--2b72d78c:140d5a4a071:-8000:0000000000000AA5 begin
{
}
// section -64--88-0-12--2b72d78c:140d5a4a071:-8000:0000000000000AA5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Bloque::getx()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-12--2b72d78c:140d5a4a071:-8000:0000000000000AA7 begin
{
}
// section -64--88-0-12--2b72d78c:140d5a4a071:-8000:0000000000000AA7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Bloque::gety()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-12--2b72d78c:140d5a4a071:-8000:0000000000000AAB begin
{
}
// section -64--88-0-12--2b72d78c:140d5a4a071:-8000:0000000000000AAB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
