#include "Cola.h"




void Cola::pop()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-12--2b72d78c:140d5a4a071:-8000:0000000000000A8E begin
{
}
// section -64--88-0-12--2b72d78c:140d5a4a071:-8000:0000000000000A8E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Cola::push()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-12--2b72d78c:140d5a4a071:-8000:0000000000000A90 begin
{
}
// section -64--88-0-12--2b72d78c:140d5a4a071:-8000:0000000000000A90 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
