#include "Figura.h"




void Figura::rotarderecha()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-12--2b72d78c:140d5a4a071:-8000:0000000000000A94 begin
{
}
// section -64--88-0-12--2b72d78c:140d5a4a071:-8000:0000000000000A94 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Figura::rotarizquierda()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-12--2b72d78c:140d5a4a071:-8000:0000000000000A96 begin
{
}
// section -64--88-0-12--2b72d78c:140d5a4a071:-8000:0000000000000A96 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
