######################################################################
# Automatically generated by qmake (3.0) Fri Sep 27 08:59:45 2013
######################################################################
Qt += widgets
TEMPLATE = app
TARGET = T3tr1s
INCLUDEPATH += .
QMAKE_CXX = clang++
QMAKE_CXXFLAGS = -std=c++11

# Input
HEADERS += Bloque.h Cola.h Figura.h gui_fig.h gui_tab.h Tablero.h
SOURCES += gui_fig.cpp gui_tab.cpp main.cpp main_gui.cpp
